version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/dev/mysql/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ro.ot+
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: u.ser+
    networks:
      - wordpress

  wordpress:
    build: docker/dev/apache
    container_name: apache
    volumes: 
      - .:/app/
      - wordpress_uploads:/app/web/app/uploads
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      TITLE: My Blog
      URL: http://localhost:8080
      ADMIN_USER: user
      ADMIN_PASSWORD: user
      ADMIN_EMAIL: email@domain.com
    networks:
      - wordpress

volumes:
    mysql_data:
    wordpress_uploads:

networks:
    wordpress:

